### ISSUE TITLE
Any plan to support XE4?

### ISSUE THREAD

**Issue by edwinyzh** [spinettaro/delphi-event-bus#1]
Thread-safe event broadcasting - this is a great concept, I don't know how do you achieve that without using Windows handle ( I assume you don't, since it supports FMX).

Most important - do you have a plan to support XE4?

**Comment by spinettaro** [comment]
There is not much work to do to support XE4. If you need support to XE4 I'll do it ASAP.

**Comment by edwinyzh** [comment]
That will be great if you make this library support XE4! I was planning to change it myself until I realized it uses the new Parallel library :)

**Comment by edwinyzh** [comment]
@spinettaro I further checked the samples, I must say this is my dream event messing library for keeping different parts of a program  decoupled, especially it's thread-safe (must to me) and it's very simple to use!

I can't wait to test the **VCL** sample when you have it support XE4 :)

**Comment by spinettaro** [comment]
Added support to Delphi2010 and major! I also created a DUnit project to facilitate testing in older version of Delphi. I tested it in XE5 and it works.

**Comment by edwinyzh** [comment]
@spinettaro, Well done! I confirm that the DUnit tests and the VCL Messaging sample compiles and runs correctly with XE4.
