### ISSUE TITLE
[Bug] Memory leaks in the TEventBus.Post() method.

### ISSUE THREAD

**Issue by edwinyzh** [spinettaro/delphi-event-bus#10]
The cloned LEvent local variable is not freed.

My partial (read only handling the freeing when in main-thread mode):
```
      for LSubscription in LSubscriptions do
      begin
        LEvent := CloneEvent(AEvent);
        PostToSubscription(LSubscription, LEvent, LIsMainThread);

        // edwin: fix memory leaks
        if AEventOwner and (LSubscription.SubscriberMethod.ThreadMode in [Posting, Main]) then
          LEvent.Free;
        // edwin end.
      end;
```

But my code doesn't free the LEvent var when in async mode...

**Comment by jkour** [comment]
It looks like this bug has been fixed after the commit in Jan, right?
You just need to free the event manually in the code.

**Comment by spinettaro** [comment]
Yes, you're right @jkour

**Comment by wxinix** [comment]
This doesn't seem to be fixed, even with the latest commit as of Aug 18, 2020.  When TEventMM = mmManual or mmManualAndFreeMainEvent,  LEvent is NEVER properly free-ed, and will result in memory leak!

The test cases do not cover mmManual and mmManualAndFreeMainEvent
