### ISSUE TITLE
Can not Post the class

### ISSUE THREAD

**Issue by TomYU6** [spinettaro/delphi-event-bus#11]
Can not Post the following class:

  TOnNotifyDocEvent = class
  private
    FData: TDictionary<string, TValue>;
  public
    constructor Create;
    destructor Destroy;override;
    property Data: TDictionary<string, TValue> read FData;
  end;

constructor TOnInfoNotifyDocDataLoadCompleteEvent.Create;
begin
    FData:= TDictionary<string, TValue>.Create;
end;

**Comment by spinettaro** [comment]
Yes, you can post only object that have simple types fields.
