### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by edwinyzh** [spinettaro/delphi-event-bus#12]
Hello,
There four event-handler invocation mode:
`TThreadMode = (Posting, Main, Async, Background);`

I use only the default (`Posting`) mode and `Main` mode (ensure the code to be run in the UI thread if it needs to access any UI controls).

But I don't quite understand the rest of the modes, care to explain a little :)

**Comment by spinettaro** [comment]
Hello!
here the differences:  

- POSTING: Subscribers will be called in the same thread posting the event  
- MAIN: Subscribers will be called in main thread
- ASYNC: Event handler methods are even called in a separate thread
- BACKGROUND: Subscribers will be called in a background thread. If posting thread is not the main thread, event handler methods will be called directly in the posting thread.
