### ISSUE TITLE
Cloned Event leaks

### ISSUE THREAD

**Issue by jkour** [spinettaro/delphi-event-bus#13]
Hi,

the cloned event in Post is not freed. I have corrected that. 

How do I push on github?

**Comment by rpottsoh** [comment]
You need to open a pull request.

**Comment by jkour** [comment]
When I do this, I can only see the master branch. I have a branch on my local repo. So, how do I upload that?

**Comment by jkour** [comment]
found it. Can you please delete this issue? and sorry for the noise here
