### ISSUE TITLE
[idea] Tiny.Rtti is 500+ faster than the system RTTI

### ISSUE THREAD

**Issue by edwinyzh** [spinettaro/delphi-event-bus#24]
Hello,

I recently discovered  [Tiny.RTTI](https://github.com/d-mozulyov/Tiny.Rtti), according to its **just-commited** benchmark demo program, as shown on the repository's github page, it's **500+** faster than `System.Rtti`! I tried to recreate the

I've no idea why it's that faster, maybe people as knowledgeable as @sglienke  can tell us something :)

And since DEB invokes the subscribing methods using `System.Rtti`, so it might be a candidate for improving the performance.

**Comment by sglienke** [comment]
Tiny.Rtti is undoubtedly faster than System.Rtti but that benchmark is comparing apples and oranges. It tests the rather high level TRttiMethod.Invoke that also uses TValue against the rather low level Tiny.Invoke where you need to mess around with pointers and stuff to do the invoke call.

And it even cheats by putting some of the work Tiny.Rtti has to do for the Invoke call outside of the measured loop!

If you want to make invocations via System.Rtti faster then use the Invoke Routine that avoids all the additional stuff happening in TRttiMethod.Invoke/DispatchInvoke but then you need to take care about all the low level parameter passing mechanisms yourself similar to Tiny.Rtti where you just pass the TRttiInvokeDump record representing registers and stack. That would rather be comparable with the implementation only routine RawInvoke from System.Rtti.

If I test `System.Rtti.Invoke(LMethod.CodeAddress, [Self, 1, 2, 3], LMethod.CallingConvention, nil);` against a non cheated Tiny.Rtti I get a difference of 5 to 1.

Additional fun fact: in my test using OptimalInvokeFunc was approx 5-10% slower than using UniversalInvokeFunc

**Comment by edwinyzh** [comment]
@d-mozulyov, comments by sglienke FYI :)

**Comment by d-mozulyov** [comment]
@edwinyzh,

The key difference is that the number of calculations is minimized, the main calculations occur at the signature analysis stage.

I also draw attention to the fact that Tiny.Rtti is not yet a full-fledged replacement for System.Rtti. Wait for new releases.
