### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by jaclas** [spinettaro/delphi-event-bus#28]
I started testing the DEB code and I have a few doubts:

1. In the examples (e.g. weather station) in the event handling methods, event objects are not released, there is a continuous memory leakage.

2. Why aren't cloned event objects released by the event bus? The bus could do this when the event handling method is returned.

3. I don't know why there are two identical methods:

```
function TEventBus.GenerateThreadProc(ASubscription: TSubscription;
  AEvent: TObject): TThreadProcedure;
start
  Result := procedure
    start
      if ASubscription.Active then
      start
        ASubscription.SubscriberMethod.Method.Invoke(ASubscription.Subscriber,
          [AEvent]);
      end;
    end;
end;

function TEventBus.GenerateTProc(ASubscription: TSubscription;
  AEvent: TObject): TProc;
start
  Result := procedure
    start
      if ASubscription.Active then
      start
        ASubscription.SubscriberMethod.Method.Invoke(ASubscription.Subscriber,
          [AEvent]);
      end;
    end;
end;
```

**Comment by spinettaro** [comment]
Hi @jaclas 
1. You are right and that one will be fixed in the next version. Including new feature: channels!
2. Because an event could be notified in a background thread. Not impossible, I know, but then hard to maintain. In addition, if the framework has to wait for a task to be completed, it could wait infinite (based on the logic of the notified method). That it's not acceptable. Any suggestion to improve that part is more than welcome but remember to respect previous assumptions.
3. Those 2 methods are for compatibility: 1 is for compiler_version>= 28 and the other one for others. 

Let me know, if those answer are ok for you. Feel free to close it, if they satisfied you.

**Comment by jaclas** [comment]
Can you explain more precisely what is the problem with release event object from tread? 

Because I think it was enough to add the release of the event object in three methods of the bus and there would be no problem:

```
function TEventBus.GenerateThreadProc(ASubscription: TSubscription;
  AEvent: TObject): TThreadProcedure;
begin
  Result := procedure
    begin
      if ASubscription.Active then
      begin
        ASubscription.SubscriberMethod.Method.Invoke(ASubscription.Subscriber, [AEvent]);
        AEvent.Free;       // <--------------- FREE EVENT
      end;
    end;
end;

function TEventBus.GenerateTProc(ASubscription: TSubscription;
  AEvent: TObject): TProc;
begin
  Result := procedure
    begin
      if ASubscription.Active then
      begin
        ASubscription.SubscriberMethod.Method.Invoke(ASubscription.Subscriber, [AEvent]);
        AEvent.Free;       // <--------------- FREE EVENT
      end;
    end;
end;

procedure TEventBus.InvokeSubscriber(ASubscription: TSubscription;
  AEvent: TObject);
begin
  try
    ASubscription.SubscriberMethod.Method.Invoke(ASubscription.Subscriber, [AEvent]);
    AEvent.Free;       // <--------------- FREE EVENT
  except
    on E: Exception do
    begin
      raise Exception.CreateFmt
        ('Error invoking subscriber method. Subscriber class: %s. Event type: %s. Original exception: %s: %s',
        [ASubscription.Subscriber.ClassName,
        ASubscription.SubscriberMethod.EventType.ClassName, E.ClassName,
        E.Message]);
    end;
  end;
end;
```

One more comment. 
Checking if AEvent is assigned is worth doing at the beginning of the Post() method, so you will avoid Access Violation exception:

```
procedure TEventBus.Post(AEvent: TObject; const AContext: String = '';
  AEventOwner: Boolean = true);
var
  LSubscriptions: TObjectList<TSubscription>;
  LSubscription: TSubscription;
  LEvent: TObject;
  LIsMainThread: Boolean;
begin
  if not Assigned(AEvent) then exit;  // <----------------   IN THIS PLACE
  FMREWSync.BeginRead;
  try
    try
      LIsMainThread := MainThreadID = TThread.CurrentThread.ThreadID;

      FSubscriptionsOfGivenEventType.TryGetValue(AEvent.ClassType, // <-----  WITHOUT CHECKING 
     // AFTER BEGIN THIS PLACE RAISE EXCEPTION IF AEVENT WAS NIL
        LSubscriptions);

      if (not Assigned(LSubscriptions)) then
        Exit;

      for LSubscription in LSubscriptions do
      begin

        if not LSubscription.Active then
          continue;

        if ((not AContext.IsEmpty) and (LSubscription.Context <> AContext)) then
          continue;

        LEvent := CloneEvent(AEvent);
        PostToSubscription(LSubscription, LEvent, LIsMainThread);
      end;
    finally
      if (AEventOwner and Assigned(AEvent)) then   // <--- THIS Assigned() IS NOW UNNECESSARY
        AEvent.Free;
    end;
  finally
    FMREWSync.EndRead;
  end;
end;
```

When are you planning to release the new version with channels?

**Comment by spinettaro** [comment]
@jaclas ok make sense your suggestion. Only one thing: should we consider AEventOwner boolean to do that? Or just by default all the events will be destroyed?

**Comment by spinettaro** [comment]
@jaclas I release channels ASAP probably today

**Comment by jaclas** [comment]
I suggest you do something else :-)
Now, when you add the release of event objects it will be a breaking change. It's a good moment to other change.
That's why I propose to change AEventOwner type to enumerate type (boolean as parameter is ..poor):

TEventObjectProcessing = (CloneAndRelease, OnlyCloneWithoutRelease, PassWithoutCloneAndRelease);

CloneAndRelease - that is clones objects and releases (as I proposed in the previous post), default mode

OnlyCloneWithoutRelease - as it was before, clones the event object but does not release it (and also does not release the main object in the Post() method as it does now!)

PassWithoutCloneAndRelease - passes the original event object (without cloning) through the bus and leaves the life cycle management outside the bus

The last mode can be useful when I have some "empty" event object which I use only to notify about some general event and I do it periodically (e.g. event when a message comes in and you have to signal it with a sound)

**Comment by spinettaro** [comment]
Your suggestion will be a breaking change. Consider current scenario:
```
procedure Post(AEvent: TObject; const AContext: String = ''; AEventOwner: Boolean = true); virtual;
```
Now this function will free the Event parameter and not the cloned ones. 
How this fit with your solution? 
I agree with the Enumerate type. But changing that we have to find a way to replicate the old behavior ( true or false ) or just do it an it will be a breaking change.

**Comment by spinettaro** [comment]
A solution could be:
```
TEventObjectProcessing = (opAutomatic, opManual, opManualExceptForMainEvent);
```
opAutomatic: this clones objects and releases them and the main parameter event as well
opManual: this doesn't do nothing - all the memory management will be manually managed
opManualExceptForMainEvent: as opManual except for the main parameter Event.

Also with this solution we cannot avoid a breaking change.
Because how we will manage the old boolean? 
What are your thoughts? 

In general I like more the breaking change scenario so the code will not contain deprecated code and it isn't a big breaking change. 

@edwinyzh  also your  feedback is important :)

**Comment by jaclas** [comment]
In my opinion it's better to breaking change AND compilation error than to break "quietly". 
So when the last Post() method parameter instead of Boolean (default = True) gets TEventProcessing = opManualExceptForMainEvent. Then the code that uses the default settings will work the same way. And the code that uses False (as AEventOwner) will stop compiling and force the user to think and improve.

**Comment by spinettaro** [comment]
@jaclas I agree. I'll put those changes into channels stuff, I'll run unit tests and I'll let you know!

**Comment by spinettaro** [comment]
@jaclas pushed changes related to channels and new EventMemoryManagement. Let me know :)

**Comment by jaclas** [comment]
Thanks! Tomorrow I will test the events and their life cycle.

As for the channels... I look at the code and see that the channels are made in a rather simplified way, only "one level" and only with a text string value.
I suggest that you look at the solution called "topics" used in MQTT. This kind of solution is much more flexible, the hierarchical structure gives a lot of possibilities. See:

https://doc-snapshots.qt.io/qtmqtt/mqtt-overview.html#topics

or see example of usage from (subscribe/publish):

https://github.com/jamiei/Delphi-TMQTT2#usage

Very important in this extended model of channels is wildcards (*) support, example: 

`[subscribe('/channels/machine/*')]`

**Comment by jkour** [comment]
@spinettaro I never understood why the bus has to free the Event objects. That shows be responsibility of the consumer of the notification. This would simplify the code and would remove the need to clone objects

**Comment by jkour** [comment]
@spinettaro For pattern matching in channel names you may find this useful: https://github.com/jkour/Motif

**Comment by wxinix** [comment]
> 
> 
> @spinettaro I never understood why the bus has to free the Event objects. That shows be responsibility of the consumer of the notification. This would simplify the code and would remove the need to clone objects

@jkour When there are multiple consumers,  the event handlers are running in different threads  for the background mode and async mode.  Cloning is necessary because the event received by each consumer has a lifetime in their respective thread.  A single event shared by different consumers,  will not work in this multi-threaded scenario.

By the way, John,  thank you for your MVVM book, and other blog articles. You are a great technical writer.

**Comment by jkour** [comment]
@wxinix Yes, I get this but I would argue that since DEB manages the life of the event objects (which means that the objects can not be freed in different threads at different times) and the objects are immutable (which does not change their content) a read-only process wouldn't be a problem.

And, thanks a lot for the kind words about the book and articles . Much appreciated.

**Comment by spinettaro** [comment]
hi @jkour  :) . @wxinix  explanation is very good. 
I'm not understanding your point. if we have to pass the object at different threads, how can we establish the right time to free it? The only way I can see it to clone the object and freeing it after that thread has finished with the object. 
Looking forward to hear from you as if you can see a better way I'll be happy to change it!

**Comment by wxinix** [comment]
> if we have to pass the object at different threads, how can we establish the right time to free it?

DEB caches all master events, and destoys them at the program termination?  This doesn't seem very memory-efficient.

Regardless,  doesn't **TEventMM.Automatic** mode already a good answer to John's comment, i.e., events will all be automatically destroyed by DEB (except the internal cloning is still needed)?

**Comment by spinettaro** [comment]
@wxinix 

> DEB caches all master events, and destoys them at the program termination? This doesn't seem very memory-efficient.

What do you mean? DEB doesn't cache all master events... It destroys them after a subscriber has done with the event. This is why cloning is needed for AsynchMode. 

About John Comment, yes I agree with you but it doesn't fit with John's point about "cloning event is not needed" .

Make sense?

**Comment by wxinix** [comment]
> > DEB caches all master events, and destoys them at the program termination? This doesn't seem very memory-efficient.
> 
> What do you mean?

Oh I meant - if we don't use cloning, while at the same time let DEB handles the life time of events, then one possible approach would be to "DEB caches all master events, and destoys them later at the program termination". In other words,  all event objects will be destroyed when the program terminates.

> doesn't fit with John's point about "cloning event is not needed" .

Not it doesn't fit.   But cloning event is really transparent to the user anyway.....

But I do have a doubt - DEB doesn't use **interface** for Event objects. Is that due to some RTTI limitation?

**Comment by jkour** [comment]
@spinettaro I've got a very similar internal library and I do what @wxinix suggests. I have a kind of internal garbage collector which cleans up periodically. 

About the interfaces, this is something that is needed and it can be implemented.

**Comment by spinettaro** [comment]
Hi all @wxinix @jkour @jaclas . In the last release I made some changes but the most important one is an Interface based architecture for the events https://github.com/spinettaro/delphi-event-bus/commit/307a2cfab813b4b56221e40ecdb6e6a3d6cdb3f4 
That remove every memory management 
@wxinix @jkour @jaclas @edwinyzh  could you have a look to EventBus.Core.pas line 154
```
    ASubscription.SubscriberMethod.Method.Invoke(ASubscription.Subscriber,
      [ AEvent as TObject  ]);
```
can you see a more elegant way to achieve the same result without using the `as TObject` cast?

I leave this open and if we cannot spot an issue I'll definitively close this one !

**Comment by wxinix** [comment]
@spinettaro thank you for the update!  It is much cleaner now after removing those unnecessary dependencies. It is also great to have interface-based Event. DEB now is a very nice light-weight Event Bus library!

 I believe "**as TObject**" cast is a must to make this new framework to work - TObject acts as a "carrier" to transfer the interface argument with the RTTI invoke.   The only nuance is that - it only works for Delphi version greater than Delphi 2010, though. 
  
I made a fork of this new DEB repository. https://github.com/wxinix/delphi-event-bus .  While reviewing the new code line by line,  I made some "cleaning up" and some reformatting to fit my own style taste, like changing String to string,  boolean to Boolean, true to True, false to False, and fixed some inconsistencies in naming conventions like some local variables forgetting to prefix with an L.  All minor things.  If you like, I can submit a pull request, but of course,   feel free to reject my changes (not a big deal).

Thank you again for this nice library. Congrats!

**Comment by wxinix** [comment]
I believe assigning IInterface to TValue then casting it to the specific interface at the subscriber method call site,  will cause cast error. This is because there won’t by automatic QueryInterface call to cast back IInterface to the specific interface. Hence we must use TObject as the “carrier”, which takes care of the QueryInterface implicitly.

**Comment by jkour** [comment]
Hi,

@spinettaro, I think `as TObject` is the way to do it; at least what I found to be the simplest way. 

I don't think it is not elegant. It is just a trick to pass the parameter without affecting the RefCount or anything else. It looks quite safe.

**Comment by spinettaro** [comment]
> @spinettaro thank you for the update! It is much cleaner now after removing those unnecessary dependencies. It is also great to have interface-based Event. DEB now is a very nice light-weight Event Bus library!
> 
> I believe "**as TObject**" cast is a must to make this new framework to work - TObject acts as a "carrier" to transfer the interface argument with the RTTI invoke. The only nuance is that - it only works for Delphi version greater than Delphi 2010, though.
> 
> I made a fork of this new DEB repository. https://github.com/wxinix/delphi-event-bus . While reviewing the new code line by line, I made some "cleaning up" and some reformatting to fit my own style taste, like changing String to string, boolean to Boolean, true to True, false to False, and fixed some inconsistencies in naming conventions like some local variables forgetting to prefix with an L. All minor things. If you like, I can submit a pull request, but of course, feel free to reject my changes (not a big deal).
> 
> Thank you again for this nice library. Congrats!

Thanks! Feel free to create a PR... any improvement is more than welcome :)

**Comment by spinettaro** [comment]
Closed after last changes.... Feel free to reopen or create a new one in case you need
