### ISSUE TITLE
A little bug in Unregister ?

### ISSUE THREAD

**Issue by gmarab** [spinettaro/delphi-event-bus#3]
I believe there is a small bug in the Unregister mechanism:
if it takes a Unregister, all those who have made a subscription for that class of events are removed.

I think the problem is the 290-292 lines of the unit EventBus.pas, where instead of:

```
 if (LSubscription.Subscriber.Equals (ASubscriber)) then
    LSubscription.Active: = false;
 LSubscriptions.Delete (I);
```

put it:

```
 if (LSubscription.Subscriber.Equals (ASubscriber)) then
 begin
   LSubscription.Active: = false;
   LSubscriptions.Delete (I);
 end;
```

But it is better if you look at the code...

Congratulations for the good work.

**Comment by spinettaro** [comment]
Thanks for the compliment and yes you're right! Can you write a small unit test that evidence the bug?
So I  make sure that the fix works and respect TDD style.

**Comment by spinettaro** [comment]
Fixed the issue and added relative unit test, thanks @gmarab
