### ISSUE TITLE
Help with memory leak reporting

### ISSUE THREAD

**Issue by skamradt** [spinettaro/delphi-event-bus#31]
Add the following to EventBus.pas which will decrement the interface counter on finalization (if set) and release allocated memory. This specifically helps in situations where your using a memory manager which reports memory leaks on shutdown.

```
finalization
  FGlobalEventBus := nil;
end.
```

**Comment by wxinix** [comment]
This is more like a bug on the memory manager side, than on the Event Bus side.  In any case,  any live IEventBus  instance should be freed upon application shutdown - the memory manager simply seems to kick in for leak testing, at the wrong time.

**Comment by spinettaro** [comment]
as mentioned from @wxinix  the global instance is an interface then freed upon application shutdown. Closing this one
