### ISSUE TITLE
DEB interfaces and datamodule

### ISSUE THREAD

**Issue by c-michail** [spinettaro/delphi-event-bus#34]
Hello,
  It seems the intefaces version of DEB does not work with datamodules ?
  Attached sample project.

Thank you
[DEB.Problem.zip](https://github.com/spinettaro/delphi-event-bus/files/5496624/DEB.Problem.zip)

**Comment by spinettaro** [comment]
@chmichael you cannot pass the event in that way.... otherwise it is an IInterface.
Here the correct code:
```
var
  lEvent: IEventHelloWorld;
begin
  GlobalEventBus.RegisterSubscriberForEvents(Self);
  lEvent:= TEventHelloWorld.Create;
  GlobalEventBus.Post(lEvent);
end;
```

or

```
procedure TDataModule38.DataModuleCreate(Sender: TObject);
begin
  GlobalEventBus.RegisterSubscriberForEvents(Self);
  GlobalEventBus.Post(TEventHelloWorld.Create as IEventHelloWorld);
end;
```

Because if you pass it directly it is passed as an IInterface and the routing will not work 
 
Cheers :)

**Comment by c-michail** [comment]
Ah! I misunderstood your new examples! It's working now! (Using the 2nd method)

Thank you :)
