### ISSUE TITLE
user defined type for TSubscriberMethod

### ISSUE THREAD

**Issue by saeedkgr** [spinettaro/delphi-event-bus#35]
It would be very usefull if Context type in TSubscriberMethod can be defined by developer , something like this

//EventBus.Develoer //new unit
const
  TSubscriberContextDefault = '';   //could change to TSubscriberContextDefault = 0
type
  TSubscriberContextType = string;   //could change to TSubscriberContextType = integer; or even flat to carry two part 

//EventBus.Subscribers unit
type
  TSubscriberMethod = class(TObject)
  private
    FEventType: TClass;
    FThreadMode: TThreadMode;
    FMethod: TRttiMethod;
    FContext: TSubscriberContextType;
...

it needed to change some lines in other units

my (and some friends) implementation of events is based on integer and a long list of integer constants and methods that could use this perfect event bus implementation

thank you.

**Comment by wxinix** [comment]
I believe a context of **string** _**type**_ would provide the best **flexibility**.  Changing its _**type**_ to **Integer** might not be a good idea for delphi_event_bus as a **general** and _**light-weight**_ EventBus solution.

**Comment by spinettaro** [comment]
I agree with @wxinix  the string type gives more flexibility... @saeedkgr  You can create your own adapter in your code to be coherent with DEB context

**Comment by saeedkgr** [comment]
it's not oppose the flexibility of string type it is about making it optional for developer to decide which type fits the whole project.
