### ISSUE TITLE
Little compatibility issue: Result := []

### ISSUE THREAD

**Issue by edwinyzh** [spinettaro/delphi-event-bus#38]
In order to compile the `vclmessaging` sample project, I had to change all `Result := []` occurrences to `SetLength(Result, 0)`.

**Comment by wxinix** [comment]
Strange, I didn't find any line of `Result := [ ]`. Which file is it in?

**Comment by edwinyzh** [comment]
one example: https://github.com/spinettaro/delphi-event-bus/blob/d6262ac8a0161c21e61ecec077bb456aa88c9b54/source/EventBus.Helpers.pas#L144

**Comment by wxinix** [comment]
I thought it was in vclmessage sample.

So you are using Delphi version < XE7.  Since DEB claims to work with Delphi > Delphi 2010, then I guess this should be corrected with a conditional compiler switch?

**Comment by edwinyzh** [comment]
I think simply change all `Result := []` occurrences to `SetLength(Result, 0)` will be just enough, because the later syntax is compatible with all Delphi versions.

**Comment by wxinix** [comment]
> I think simply change all `Result := []` occurrences to `SetLength(Result, 0)` will be just enough, because the later syntax is compatible with all Delphi versions.

@edwinyzh 
Actually, **neither** `Result := [] ` **nor**  `SetLength(Result, 0)` is needed.   **Dynamic array is managed type; as such, it is auto-initialized to nil**.   You can verify this by going to Disassembly code (e.g., like below):

![2020-11-10_9-48-51](https://user-images.githubusercontent.com/5317912/98691700-4f471300-233c-11eb-9425-7c89d1f9879a.png)

But of course, for readability, it is probably better to explicitly initialize it.

**Comment by edwinyzh** [comment]
@wxinix ,

Good finding! But it might depends on the version of the compiler. In the past I have had strange, not-happen-all-the-time issues with situations where a function returns uninitialized `result`.
And according to the Delphi language spec, you must initialize the return value of a function/method.

**Comment by wxinix** [comment]
@edwinyzh  I think this has been addressed in the latest copy of EventBus.Subscribers.pas:
![2020-12-05_8-23-05](https://user-images.githubusercontent.com/5317912/101244223-20218880-36d3-11eb-87c1-a92bf59d1243.png)

**Comment by edwinyzh** [comment]
Thanks! In the near future for the current projects I'll be sticking with the old, TObject-based version. But definitely will use the new version for new projects.

**Comment by edwinyzh** [comment]
And tried to compile it with Delphi Xe4 and I got:
```
[dcc32 Error] EventBus.pas(228): E2003 Undeclared identifier: 'TTypeKind'
[dcc32 Error] EventBus.pas(252): E2005 'TTypeKind' is not a type identifier
[dcc32 Error] EventBus.pas(261): E2005 'TTypeKind' is not a type identifier
[dcc32 Error] EventBus.pas(274): E2005 'TTypeKind' is not a type identifier
```

**Comment by spinettaro** [comment]
Hi @edwinyzh , if you would like to be a maintainer of XE4 version you can create a PR. I don't have any project on that version of Delphi. If we find a maintainer is ok otherwise I'm going to close this issue.

**Comment by edwinyzh** [comment]
@spinettaro , sorry, I have to stick to the old TObject-based version for now...
