### ISSUE TITLE
infinite loop in TRTTIUtils.Clone

### ISSUE THREAD

**Issue by edwinyzh** [spinettaro/delphi-event-bus#4]
Hello Daniele,

So I've just started integrating delphi-event-bus into my program.
The first issue I'm experiencing is that, `TEventBus.Post` will be in a dead-loop in line 162,  which calls `TRTTIUtils.Clone`, which in turn loop infinitely in line 827:

```
if Field.GetValue(cloned).IsEmpty then
        begin
          targetObject := TRTTIUtils.Clone(sourceObject); // infinite loop here...
```

I guess it must has something to do with my event definition:

```
  // Base event about a TWoDoc
  TBaseDocEvent = class(TBaseAppEvent)
  private
    FDoc: TWoDoc;
  public
    property Doc: TWoDoc read FDoc write FDoc;
  end;
```

Where TWoDoc has properties like 

```
   property ParentDoc: TWoDoc read FDoc write FDoc;
   property NextSibling: TWoDoc read FDoc write FDoc;
   // and so on...
```

I wish you can shed some light on the issue, thanks.

**Comment by edwinyzh** [comment]
Update 1:
Fixed the issue by replacing `TRTTIUtils.Clone` with `LEvent := ObjectClone.TObjectClone.From(AEvent);`

ObjectClone is from [delphihaven.wordpress.com](https://delphihaven.wordpress.com/2011/06/09/object-cloning-using-rtti/)

But I'm not sure if that will introduce any other issues...

**Comment by spinettaro** [comment]
Hi Edwin, 
The RTTIUtilsU.pas is an external unit from [Delphi MVC](https://github.com/danieleteti/delphimvcframework) . Can you write a unit test to reproduce the bug ?  So I can verify it on DMVC.

**Comment by edwinyzh** [comment]
I guess the issue is about circular reference of objects, but I'm not sure.
I'm not able to provide a unit test, but if a screen-recording (showing the Delphi IDE's stack tracing ,etc) would help I could make one, and send you privately.

**Comment by spinettaro** [comment]
Thanks Edwin, but don't worry I'll create the unit test.

**Comment by spinettaro** [comment]
Removed the internal CloneEvent as the new architecture is interfaced based https://github.com/spinettaro/delphi-event-bus/commit/307a2cfab813b4b56221e40ecdb6e6a3d6cdb3f4
