### ISSUE TITLE
lock in eventbus class is a class var

### ISSUE THREAD

**Issue by sglienke** [spinettaro/delphi-event-bus#40]
Given the possibility to create multiple event bus instances and the non existence of any other class vars I think the lock should be instance wise and not the same lock for possibly multiple instances.

**Comment by spinettaro** [comment]
@sglienke  it makes absolute sense ! 
@wxinix sent a PR with the fix 

thanks both :)

**Comment by spinettaro** [comment]
fixed by @wxinix  
 @sglienke feel free to reopen it if you spot something wrong
