### ISSUE TITLE
Error Undeclared TEventBusFactory

### ISSUE THREAD

**Issue by conectvideo** [spinettaro/delphi-event-bus#49]
Hi Guys,

I try use but error [dcc32 Error] EventBus.pas(272): E2003 Undeclared identifier: 'TEventBusFactory'

Show in unit Eventub

function GlobalEventBus: IEventBus;
begin
  Result := TEventBusFactory.GlobalEventBus;
end;

The error is on my project because i do a pompile from your samples and no show errors

**Comment by wxinix** [comment]
So you have EventBus.Core.pas on search path or part of the project?

**Comment by conectvideo** [comment]
Yes

[cid:image001.png@01D6D396.637A1A70]
[cid:image004.png@01D6D396.6BD69B30]

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: Wuping Xin<mailto:notifications@github.com>
Enviado:quarta-feira, 16 de dezembro de 2020 10:25
Para: spinettaro/delphi-event-bus<mailto:delphi-event-bus@noreply.github.com>
Cc:Mauricio Abreu<mailto:conectsolutions@hotmail.com>; Author<mailto:author@noreply.github.com>
Assunto: Re: [spinettaro/delphi-event-bus] Error Undeclared TEventBusFactory (#49)

So you have EventBus.Core.pas on search path or part of the project?

**Comment by wxinix** [comment]
TEventBusFactory is defined in EventBus.Core.pas, if the compiler cannot find it, then you must have mixed old versions of event bus with the latest. Probably you might want to download the latest repo again.

**Comment by conectvideo** [comment]
Ok thanks its everything is ok now.

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: Wuping Xin<mailto:notifications@github.com>
Enviado:quarta-feira, 16 de dezembro de 2020 10:44
Para: spinettaro/delphi-event-bus<mailto:delphi-event-bus@noreply.github.com>
Cc:Mauricio Abreu<mailto:conectsolutions@hotmail.com>; Author<mailto:author@noreply.github.com>
Assunto: Re: [spinettaro/delphi-event-bus] Error Undeclared TEventBusFactory (#49)


TEventBusFactory is defined in EventBus.Core.pas, if the compiler cannot find it, then you must have mixed old versions of event bus with the latest. Probably you might want to download the latest repo again.
