### ISSUE TITLE
Contributed a wiki file

### ISSUE THREAD

**Issue by edwinyzh** [spinettaro/delphi-event-bus#5]
Hello,

I've just write a little info here: [Some notes on using delphi event bus](https://github.com/edwinyzh/delphi-event-bus/wiki/Some-notes-on-using-delphi-event-bus)

But I don't know how to contribute it back to this master repository, any help :)

**Comment by spinettaro** [comment]
Hi,
first of all thanks for your work. We can do as described here:  https://gist.github.com/larrybotha/10650410 . What do you think about?

**Comment by edwinyzh** [comment]
Thanks. I'll study it later.
