### ISSUE TITLE
Hang on splash screen

### ISSUE THREAD

**Issue by esseredigitale** [spinettaro/delphi-event-bus#50]
Hi,
I created a new app, included EventBus and then ran it on an Android device and it started regularly.
Right after I added System.Messaging, I run and 8 times out of 10 it doesn't start and stays on the splash screen.
BR

**Comment by spinettaro** [comment]
Hi @esseredigitale ,

can you provide a test project? did you start to see the exception just after you added DEB library?

**Comment by esseredigitale** [comment]
Hi @spinettaro 
https://1drv.ms/u/s!Aj-4lQEtPyPlhbxpk9pxdHnaPju6Lg?e=8wLqwP here a simple test project.
Unfortunately I don't see any exceptions! the application does not start and remains at the splash screen

**Comment by spinettaro** [comment]
@esseredigitale which version of Delphi are you using?

**Comment by esseredigitale** [comment]
> @esseredigitale which version of Delphi are you using?

10.3.3

**Comment by spinettaro** [comment]
@esseredigitale  I have just tried the AccessRemoteData sample and it works fine. Could you share again your project? in the mean time could you try a Sample project? If they work fine it is not DEB

**Comment by esseredigitale** [comment]
here my demo project https://1drv.ms/u/s!Aj-4lQEtPyPlhbxpk9pxdHnaPju6Lg?e=7K0h42

**Comment by spinettaro** [comment]
@esseredigitale  I tested your project with Delphi 10.4 and it works fine. In the past I have always tested DEB sample projects with all Delphi versions and I never had an hang on splash screen. It is something related with your IDE/Configuration. Unfortunately I don't have a 10.3.3 version to test with your specific project.

**Comment by esseredigitale** [comment]
> @esseredigitale I tested your project with Delphi 10.4 and it works fine. In the past I have always tested DEB sample projects with all Delphi versions and I never had an hang on splash screen. It is something related with your IDE/Configuration. Unfortunately I don't have a 10.3.3 version to test with your specific project.

Ok, but removing DEB from project, It works correctly!
Thanks for support
