### ISSUE TITLE
Create Groups of Observers

### ISSUE THREAD

**Issue by jkour** [spinettaro/delphi-event-bus#6]
Hi,
at the moment, the Event Bus creates a global (default) event bus to manage the the communication. This means that every time a message is being post, all the subscribers receive it and react on it.

May I suggest to create something like groups of subscribers?

They can be registered like this:
TEventBus.GetDefault.RegisterSubscriber('Group 1', self);

and send messages like this:
TEventBus.GetDefault.post('Group 1', LEvent);

An observer can be, also, subscribed like this:
[Subscribe ('Group 1')]
procedure OnEvent(AEvent: TAnyTypeOfEvent);
begin
  // manage the event 	
end;

Before I try to do it myself, I wanted to check with you if this is something that you would be interested in bringing into your project.

Thanks

**Comment by spinettaro** [comment]
Hi!
Yes I had in mind to create something like that. But I didn't think as a group as form of aggregation but something like context. You can specify the Context in the attribute (like your example above), and when an event was fired, DEB filter the right subscribers by the type of event and the context. The concept is the same that you have exposed but I think Context instead Group makes the concept more understandable. What do you think about? (I wrote something similar to [DelphiEntitiesValidators](https://github.com/bittimeprofessionals/delphi-entities-validators) )

**Comment by jkour** [comment]
Hi,

I agree that "context" may be a better term to use rather than "group".

Also one should be able to subscribe the same observer to multiple context by using the [Subscribe] attribute multiple times.

**Comment by edwinyzh** [comment]
I noticed today's commit contains the change for the support of contextual events. Thanks @spinettaro

**Comment by spinettaro** [comment]
Implemented with commit 79aaddb
