### ISSUE TITLE
[Question] "Active" property in TSubscription - how to use it?

### ISSUE THREAD

**Issue by Voscha** [spinettaro/delphi-event-bus#67]
Hello,
I want to know how I can use the "Active" property of TSubscription? I don't see any method to put them out of my program code. What is the correct way to disable the notification?

**Comment by spinettaro** [comment]
Hi @Voscha, if I understood well you want to stop receiving notification. That happens simply unregistering the Subscriber: ` GlobalEventBus.UnregisterForEvents(Subscriber); ` 

Let me know if that is what you were looking for :)

**Comment by Voscha** [comment]
Hi Daniele, I would like to know what is the meaning of the active property of TSubscription and how can I use it? My idea was to use this property to temporarily turn off the reception of notifications. But you're right. I can also use 'register' and 'unregister' at any time. good luck with tonight's game! 🏆⚽

**Comment by spinettaro** [comment]
Hi @Voscha Active property of TSubscription is used for internal mechanisms of the framework, then the correct way is to use Register and Unregister :)
