### ISSUE TITLE
TList inside posted event objects empties on Delphi 11 Alexandria 

### ISSUE THREAD

**Issue by JosephBashful** [spinettaro/delphi-event-bus#68]
if posted event object contains a TList, that TList arrive empty to subscribers.

I make a simple application to demostrate that
[TestDEBIssue.zip](https://github.com/spinettaro/delphi-event-bus/files/7331137/TestDEBIssue.zip)

Place a breakpoint on frmMain, on line 62
Evalueting AEvent.List result this

**On Delphi 10.4 Sydney**
`(((('test', False, 20), nil, nil, nil), 1, $850538, $32F9310, nil, nil), Pointer($863C4C) as {System.Generics.Defaults}IComparer<frmMain.TTestObject>, (nil,nil), 1)`

**On Delphi 11.0 Alexandria**
`((nil, nil, nil, nil), 1, $7C4004, $30E4AA0, nil, nil, Pointer($7D7D58) as {System.Generics.Defaults}IComparer<frmMain.TTestObject>, (nil,nil))`

As you can see, on Alexandria the TList part arrive filled with nils

**Comment by spinettaro** [comment]
Hi @JosephBashful , I tested your application and it is working with the new version of DEB. Not sure which version you are using but the latest one works correctly. Here the project you sent me modified for the last version of DEB
[TestDEBIssueNewDEB.zip](https://github.com/spinettaro/delphi-event-bus/files/7333140/TestDEBIssueNewDEB.zip)

LEt me know

**Comment by JosephBashful** [comment]
Hi @spinettaro,
i'm sorry for the late reply.
We checked the code and you were right, we were not using the latest version (we used wrong path on library path, pointing on a previous version).
No problem with latest version.
Thank you
