### ISSUE TITLE
Make the project compatible under XE4 or so

### ISSUE THREAD

**Issue by edwinyzh** [spinettaro/delphi-event-bus#7]
Uses `System.JSON` in new versions while using `Data.DBXJSON` in older versions, for example, XE4.

Thanks.

**Comment by swanitzek** [comment]
Yes please. The readme says 'it works with Delphi2010 and major' but as of my understanding you need at least XE6 to get it running.

**Comment by spinettaro** [comment]
@swanitzek resolved with last commit. I didn't have Delphi2010, can you test this?

**Comment by swanitzek** [comment]
@spinettaro  The oldest version I have access to is XE2. 

It does not work with XE2 (Compile time error in ObjectMappers:41)
> E2029 $IFEND expected, but $ENDIF found.

If I compile it with XE5 everything works as expected (verified with Analytics-example).

**Comment by spinettaro** [comment]
@swanitzek it's ok for you? XE5 and upper?

**Comment by swanitzek** [comment]
For me it's OK. Thank you.
