### ISSUE TITLE
DEB on Android

### ISSUE THREAD

**Issue by neo4a** [spinettaro/delphi-event-bus#71]
Firemonkey project is working well on Windows platform but will fail on Android.

Is there any chance for getting support of mobile platforms by DEB?

**Comment by TomYU6** [comment]
I use it on the Android platform without any problems.

**Comment by spinettaro** [comment]
@neo4a DEB supports Firemonkey as it is OS and framework independent code. It is just pure Delphi, Something wrong in your project
