### ISSUE TITLE
Background / Async tasks deadlock

### ISSUE THREAD

**Issue by SwiftExpat** [spinettaro/delphi-event-bus#73]
Deb uses TTaskRun, which submits to a shared threadpool. When multiple events are fired quickly, the app deadlocks and does not recover.  I have fixed this by creating a threadpool for DEB and modifying the run to use that threadpool.
Before:  
`TTask.Run(LProc);`
After:  
`TTask.Run(LProc, FDebThreadPool);`

Pull request for fix is: #74 
If anyone has an example of using TThreadPoolStats to check the health of that thread pool before the task runs it would be great to see to ensure the pool is healthy enough not to deadlock later.

**Comment by spinettaro** [comment]
Yep, it makes more sense to have a dedicated ThreadPool
